In [2]:
import numpy as np

## random_state — свой генератор для воспроизводимости

Вместо глобального `np.random.seed` создаём отдельный генератор.
Одинаковый `seed` → одинаковые числа.

In [4]:
# создаём генератор со своим seed
random_state = np.random.RandomState(42)
random_state.rand(10)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
       0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258])

In [ ]:
array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
       0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258])

In [ ]:
# тот же seed — те же числа (воспроизводимость)
rs1 = np.random.RandomState(42)
rs2 = np.random.RandomState(42)
print(rs1.randint(0, 100, 5))
print(rs2.randint(0, 100, 5))

In [ ]:
[51 92 14 71 60]
[51 92 14 71 60]

In [ ]:
# другой seed — другие числа
rs = np.random.RandomState(0)
rs.randint(0, 100, 5)

In [ ]:
array([44, 47, 64, 67, 67])