In [1]:
import numpy as np
import pandas as pd

In [34]:
a = [1, "a", max, 1.4]

In [36]:
a = [1,4,5,6,7,8]

In [37]:
a[3] = "a"

In [38]:
a

[1, 4, 5, 'a', 7, 8]

## Способы создать numpy-массив

In [45]:
# из обычного списка
f = np.array([1, 2, 3, 4])
f

array([1, 2, 3, 4])

In [54]:
# arange: от 0 до 10 с шагом 2
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [56]:
# массив из нулей заданной формы (2 строки, 3 столбца)
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [63]:
# массив из единиц заданной формы (2 строки, 3 столбца)
np.ones((10, 10))*7

array([[7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

In [58]:
# linspace: 5 равномерных точек от 0 до 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [59]:
# случайный массив 2x3 из чисел [0, 1)
np.random.rand(2, 3)

array([[0.21785255, 0.47633552, 0.44123945],
       [0.50574039, 0.07538107, 0.4969944 ]])

## Двумерные массивы и форма (shape)

In [64]:
# нули: 3 строки, 4 столбца
a = np.zeros((3, 4))
print(a)
print("shape:", a.shape)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
shape: (3, 4)


In [65]:
# единицы: 2 строки, 5 столбцов
b = np.ones((2, 5))
print(b)
print("shape:", b.shape)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
shape: (2, 5)


In [70]:
# 12 чисел в одну строку
c = np.arange(12)
print(c)
print("shape:", c.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
shape: (12,)


In [71]:
c.reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [81]:
c = np.arange(1000_000_000)

In [ ]:
c.reshape(100, 10, 10, 10, 10_00)

In [67]:
# те же 12 чисел как 3 строки, 4 столбца
d = np.arange(12).reshape(3, 4)
print(d)
print("shape:", d.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
shape: (3, 4)


In [68]:
# те же 12 чисел как 2 строки, 6 столбцов
e = np.arange(12).reshape(2, 6)
print(e)
print("shape:", e.shape)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
shape: (2, 6)


## Срезы (slicing) одномерного и двумерного массива

In [20]:
# одномерный массив для примеров
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
# первые 3 элемента
arr[:3]

array([0, 1, 2])

In [22]:
# последние 2 элемента
arr[-2:]

array([8, 9])

In [23]:
# двумерный массив для примеров (4 строки, 4 столбца)
mat = np.arange(16).reshape(4, 4)
mat

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [27]:
# под-блок: первые 2 строки и первые 2 столбца
g = mat[:, :2]

## Булева маска: оставить числа больше 0.5

In [32]:
# 20 случайных чисел от 0 до 1
nums = np.random.rand(20)
nums

array([0.57495051, 0.70063706, 0.8483837 , 0.65230178, 0.32172149,
       0.56833256, 0.16411798, 0.7617187 , 0.44584786, 0.24966455,
       0.83718348, 0.94582359, 0.07596592, 0.66737928, 0.61300322,
       0.70516771, 0.14599087, 0.23115645, 0.02980688, 0.92354881])

In [33]:
# оставляем только те, что больше 0.5
# [n for n in nums if n > 0.5 ]

nums[nums > 0.5]

array([0.57495051, 0.70063706, 0.8483837 , 0.65230178, 0.56833256,
       0.7617187 , 0.83718348, 0.94582359, 0.66737928, 0.61300322,
       0.70516771, 0.92354881])

## Датасет titanic из seaborn

In [40]:
import seaborn as sns

# загружаем встроенный датасет
df = sns.load_dataset('titanic')
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True


In [41]:
# размер таблицы (строки, столбцы)
df.shape

(891, 15)

## Первый взгляд на данные: head, tail, shape, info, describe, dtypes

In [43]:
# первые 5 строк
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True


In [44]:
# последние 5 строк
df.tail()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
886,0,2,male,27.0,0,0,13.00,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.00,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.45,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.00,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.75,Q,Third,man,True,NaN,Queenstown,no,True


In [45]:
# размер таблицы (строки, столбцы)
df.shape

(891, 15)

In [46]:
# общая информация: столбцы, типы, пропуски
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


In [47]:
# статистика по числовым столбцам
df.describe()

,survived,pclass,age,sibsp,parch,fare
count,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200


In [ ]:
# тип данных каждого столбца
df.dtypes

## Выбор столбцов и строк: loc vs iloc

In [ ]:
# один столбец — это Series
df['age'].head()

In [ ]:
# два столбца — список имён в [[ ]], это DataFrame
df[['age', 'fare']].head()

In [ ]:
# loc — по метке индекса (здесь метки совпадают с номерами): строки 0..4
df.loc[0:4]

In [ ]:
# iloc — по номеру позиции: строки 0..4 (правый край НЕ включается)
df.iloc[0:5]

## Фильтрация строк по условию

In [65]:
# пассажиры старше 30 лет
t = df[df['age'] > 30]

In [66]:
a = pd.DataFrame({
    "age": [10, 15, 20, 25, 23, 17],
    "height": [90, 160, 170, 175, 165, 160],
})

In [68]:
a

,age,height
0,10,90
1,15,160
2,20,170
3,25,175
4,23,165
5,17,160


In [76]:
fil = (a["age"] > 18) & (a["height"] < 170)

In [77]:
fil

0    False
1    False
2    False
3    False
4     True
5    False
dtype: bool

In [78]:
a[fil]

,age,height
4,23,165


In [73]:
a[a["age"] > 18]

,age,height
2,20,170
3,25,175
4,23,165


In [60]:
t.info()

<class 'pandas.core.frame.DataFrame'>
Index: 305 entries, 1 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     305 non-null    int64   
 1   pclass       305 non-null    int64   
 2   sex          305 non-null    object  
 3   age          305 non-null    float64 
 4   sibsp        305 non-null    int64   
 5   parch        305 non-null    int64   
 6   fare         305 non-null    float64 
 7   embarked     303 non-null    object  
 8   class        305 non-null    category
 9   who          305 non-null    object  
 10  adult_male   305 non-null    bool    
 11  deck         115 non-null    category
 12  embark_town  303 non-null    object  
 13  alive        305 non-null    object  
 14  alone        305 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 30.3+ KB


In [63]:
# выжившие пассажиры (survived == 1)
df[df['survived'] == 1].info()

<class 'pandas.core.frame.DataFrame'>
Index: 342 entries, 1 to 889
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     342 non-null    int64   
 1   pclass       342 non-null    int64   
 2   sex          342 non-null    object  
 3   age          290 non-null    float64 
 4   sibsp        342 non-null    int64   
 5   parch        342 non-null    int64   
 6   fare         342 non-null    float64 
 7   embarked     340 non-null    object  
 8   class        342 non-null    category
 9   who          342 non-null    object  
 10  adult_male   342 non-null    bool    
 11  deck         136 non-null    category
 12  embark_town  340 non-null    object  
 13  alive        342 non-null    object  
 14  alone        342 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 33.9+ KB


In [64]:
# два условия вместе: & (и), | (или).
# каждое условие в скобках — иначе ошибка из-за приоритета операций.
# обычный and/or тут не работает: нужен поэлементный & для массивов.
df[(df['age'] > 30) & (df['survived'] == 1)].head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
15,1,2,female,55.0,0,0,16.0000,S,Second,woman,False,NaN,Southampton,yes,True
21,1,2,male,34.0,0,0,13.0000,S,Second,man,True,D,Southampton,yes,True


## Сколько выжило и сколько погибло?

In [ ]:
# счёт: 0 — погибли, 1 — выжили
df['survived'].value_counts()

In [ ]:
# доли в процентах
df['survived'].value_counts(normalize=True) * 100

## Кого больше — мужчин или женщин?

In [ ]:
# считаем, сколько пассажиров каждого пола
df['sex'].value_counts()

## Кто выживал чаще — мужчины или женщины?

In [ ]:
# группируем по полу и берём среднее survived — это доля выживших
df.groupby('sex')['survived'].mean()

## У какого класса лучшая выживаемость?

In [ ]:
# группируем по классу и берём долю выживших
df.groupby('pclass')['survived'].mean()

## Средний возраст пассажиров

In [ ]:
# средний возраст
df['age'].mean()

## У скольких пассажиров не указан возраст?

In [95]:
# сколько пропусков в столбце age
df['age'].isnull().sum()

177

In [96]:
# сколько это в процентах от всех пассажиров
df['age'].isnull().sum() / len(df) * 100

19.865319865319865

## Выживали ли чаще те, кто заплатил больше?

In [94]:
# средний билет у выживших и погибших
df.groupby('survived')['fare'].mean()

survived
0    22.117887
1    48.395408
Name: fare, dtype: float64

## Дети выживали чаще взрослых?

In [ ]:
# делим возраст на группы: до 18 — ребёнок, иначе взрослый
df['age_group'] = np.where(df['age'] < 18, 'ребёнок', 'взрослый')
df['age_group'].value_counts()

In [ ]:
# доля выживших в каждой возрастной группе
df.groupby('age_group')['survived'].mean()

## «Женщины и дети — вперёд» — правда ли это?

In [104]:
def category(st):
    if st['age'] < 18:
        return 'ребёнок'
    elif st['sex'] == 'female':
        return 'женщина'
    else:
        return 'мужчина'

# применяем к каждой строке
df['category'] = df.apply(category, axis=1)
df['category'].value_counts()

category
мужчина    519
женщина    259
ребёнок    113
Name: count, dtype: int64

In [105]:
# доля выживших по категориям, от большей к меньшей
df.groupby('category')['survived'].mean().sort_values(ascending=False)

category
женщина    0.752896
ребёнок    0.539823
мужчина    0.165703
Name: survived, dtype: float64

# ПЕРЕРЫВ ДО 11:45

In [106]:
sns.load_dataset("erundu")

ValueError: 'erundu' is not one of the example datasets.

## Какие ещё датасеты есть в seaborn?

In [107]:
# список всех встроенных датасетов seaborn
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [108]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,age_group,категория,category
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,взрослый,мужчина,мужчина
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,взрослый,женщина,женщина
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,взрослый,женщина,женщина
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,взрослый,женщина,женщина
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,взрослый,мужчина,мужчина
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True,взрослый,мужчина,мужчина
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True,взрослый,женщина,женщина
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False,взрослый,женщина,женщина
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True,взрослый,мужчина,мужчина


## 10 самых старших выживших пассажиров

In [109]:
# берём выживших, сортируем по возрасту от старших к младшим, первые 10
df[df['survived'] == 1].sort_values('age', ascending=False).head(10)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,age_group,категория,category
630,1,1,male,80.0,0,0,30.0000,S,First,man,True,A,Southampton,yes,True,взрослый,мужчина,мужчина
275,1,1,female,63.0,1,0,77.9583,S,First,woman,False,D,Southampton,yes,False,взрослый,женщина,женщина
483,1,3,female,63.0,0,0,9.5875,S,Third,woman,False,NaN,Southampton,yes,True,взрослый,женщина,женщина
829,1,1,female,62.0,0,0,80.0000,NaN,First,woman,False,B,NaN,yes,True,взрослый,женщина,женщина
570,1,2,male,62.0,0,0,10.5000,S,Second,man,True,NaN,Southampton,yes,True,взрослый,мужчина,мужчина
366,1,1,female,60.0,1,0,75.2500,C,First,woman,False,D,Cherbourg,yes,False,взрослый,женщина,женщина
587,1,1,male,60.0,1,1,79.2000,C,First,man,True,B,Cherbourg,yes,False,взрослый,мужчина,мужчина
268,1,1,female,58.0,0,1,153.4625,S,First,woman,False,C,Southampton,yes,False,взрослый,женщина,женщина
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True,взрослый,женщина,женщина
195,1,1,female,58.0,0,0,146.5208,C,First,woman,False,B,Cherbourg,yes,True,взрослый,женщина,женщина
